
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres_db
      SPRING_DATASOURCE_USERNAME: pg
      SPRING_DATASOURCE_PASSWORD: post123
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=post123
  